### ISSUE TITLE
Looking for changes - Takes a lot of time

### ISSUE THREAD

**Issue by Zakay** [EugenMayer/docker-sync#532] opened 2018-03-01 11:40 UTC
Even when stoping docker sync, running the clean command, removing all containers.

When starting the environment from scratch, looking for changes takes huge amount of times, minutes.

Is there cache some where else it tries to compare against? Or is this text outputed even when it has nothing to compare, then what actually happens at this stage?

**Comment by EugenMayer** [comment] 2018-03-08 07:42
Please read https://github.com/EugenMayer/docker-sync/issues/517 - closing as duplicate

**Closed by EugenMayer** 2018-03-08 07:42 UTC

**Comment by Zakay** [comment] 2018-03-08 08:44
@EugenMayer I don't see how these are duplicates. That was a long thread, but this is not about synchronisation stopping or slow. It's merely the startup time I'm talking about, before sync is even starting. Would be nice to get a comment about this or how this is similar to the other issue. Cause I also experience sync stopping sometimes, this I mention is basically every startup.

**Comment by EugenMayer** [comment] 2018-03-08 08:47
so its a d4m question :)

yes, starting with d4m 45 or 42+ startup times are massivlt higher, while speed is a little faster - that has though nothing to do with docker-sync, it is a general "thing" .. when you downgrade to 42 startup will be a lot faster - the reasons behind that are d4m related, starting a stack with or without docker-sync, startup will be the same ( either fast or slow )

**Comment by EugenMayer** [comment] 2018-03-08 08:49
and if you are talking about how long docker-sync needs to startup, it depends on the amount of files, your i/o throughput and all this. Cound your files, ensure you really need that amount of files to be synced, adjust your sync_excludes accordingly. Most people sync node_modules and a vendor and a lot more, which is just wrong.

You neither will ever change anything in those folders on, so sync does not make sense, nor are node_modules cross-platform and can be synced from the host to the docker-container. 

Ensure you run all npm install, composer install, whatever packager inside your VM

**Comment by Zakay** [comment] 2018-03-08 09:11
Ok sure, we have huge amount of files, but this became an issue I guess with docker updates then.
I was thinking docker-sync because it says "Looking for changes" which sounds like there is two sets of files which it needs to check for differences in. 

That why I got confused, cause even on a clean startup it displayed this message for a long amount of time.

So basically even the first copy of files takes this long? Couldn't there be a different/faster way copying the files the first time before even trying to sync? Mounting differently, copying differently and then enabling sync after the copy is complete.

Not sure how it internally works, so I'm just throwing some ideas.

**Comment by mantenie** [comment] 2018-04-18 08:15
Hi @Zakay,

I experienced exactly the same. My project is a small ruby application but the initial "Looking for changes" takes a lot of time. Did you find a solution?

**Comment by Zakay** [comment] 2018-04-18 09:54
@mantenie Hi, unfortunately I don't have a solution for this, just hoping it can get solved. It's a constant pain in our workflow. I haven't had the time to dig into the internal to find out how stuff works. But my guess based on absolutely no knowledge of the internals, is that unison syncing of a huge amount of files, per file, is a slow process. If the problem is the per file syncing, I would on an initial sync, just transfer the files without a sync protocol, just copy them over, either file by file or "bundle them -> copy -> unbundle" then activate sync.

**Comment by EugenMayer** [comment] 2018-04-18 12:38
@Zakay not wrong, but not entirely true either. unison creates a file catalog on the initial sync and this takes long, speeds up later syncs a lot. so lets say if you docker cp the files on the destination first, and the run unison, even though nothing will get synced initially, the catalog creation will take time. this said, it's still can be beneficial, but you need to test that.

the problem with docker-sync is, most people want to just use it, but investing time into it seems not to be an option often.

considering the pain an time you loose in the team it might actually save you some time.

**Comment by Zakay** [comment] 2018-04-18 13:16
@EugenMayer I don't want to be negative at all towards your work here, I wouldn't be using Docker on a mac if it weren't for you! It literally makes docker usable for our use-case.

Having a project open source and on a public "forum" like this means that you will receive tons of feedback and issue reports. Most people wont have the time to invest nor the knowledge to fix these issues them selfes. Most people if not all using docker-sync are super grateful, if I may speak on behalf of the rest 😄. I personally admire all open source project maintainers.

This issue right here is one of the issues we encounter, unfortunately it got closed (for some reason of being a duplicate issue) but thats fine. It's a small issue when you compare it to running docker for mac without docker-sync.

To keep the discussion going on this matter, I would modify my above statement to add building of this unison catalog together with the bundling of the files and making sure unison starts on that catalog file. Still guessing but I would bet it would make the process much quicker, cause on syncing it does most likely does file operations on both sides. Of course this would require a greater effort to build, and I wouldn't be that sure that its the right thing to focus on or if it's even within the scope of this project.

There are probably other issues people report that most likely is a 3rd-party problem and definitely out of scope. I remember being part of the discussion on such an issue earlier.

If you think it's within the scope of the project and doable, I would hope for an issue to be open and labeled with "Pr's are welcome" and see what happens.

**Comment by Startouf** [comment] 2020-06-30 20:06
Is this a duplicate of #514 actually ?
