### ISSUE TITLE
Flood of [unox][WARN]: unexpected file event at path

### ISSUE THREAD

**Issue by mickaelperrin** [EugenMayer/docker-sync#117] opened 2016-08-19 08:59 UTC
Hi,

Unox may flood a lot of `warning` messages like: `[unox][WARN]: unexpected file event at path`.

In my case, they were triggered by the `backupd` process.

Should we display those messages (1 message per file...) ? If no, which strategy to handle this ? parse the output ? fork `unox` to prevent the display of the error message ?

**Comment by mickaelperrin** [comment] 2016-08-19 09:34
It looks like it is not only a cosmetic problem... it prevents the syncing to behave normally...

**Comment by EugenMayer** [comment] 2016-08-19 09:57
I also go told by an employee, that sync stopped in some cases, but i am yet not sure for the reasons. I have for now far more issues with unison then with rsync, so we need to harden it a little more to make it the default i guess. I also opened several issues, also conceptional once like #116 or #108  becomes even more critical. 

We maybe have to sprint onces, to bring some light into those issues - its not yet clear which one do relate to each other, maybe even to this one

**Comment by mickaelperrin** [comment] 2016-08-19 10:23
Currently, I don't see how we could resolve this elegantly... :(

I got it working by disabling / excluding the folder from backups of time machine. While the code may be pushed outside the computer, this is for sure not the desired behaviour...

I suspect also all indexing process (dropbox like, spotlight...) to interfere...

**Comment by EugenMayer** [comment] 2016-08-19 10:26
can we somehow ignore this even in general, or does unox yet not support this event at all?

**Comment by mickaelperrin** [comment] 2016-08-19 10:32
I think the problem is the flood occasionated by the event, `unox` simply ignore it and echoes a warning message.

`fs_usage` helps to see which process is at the origin of the filechange. I am wondering if libraries like `fsevents` can introduce filters on process names. I haven't found anything so far and I am even wondering if they can access that kind of information...

**Comment by mickaelperrin** [comment] 2016-08-19 10:47
Even with excluding time machine / spotlight / dropbox... I continue to get the flood.

`fs_usage` doesn't report any suspect activity... Does the problem may come from the container ??

**Comment by mickaelperrin** [comment] 2016-08-19 11:25
Finally, a reboot of the machine helps me to get a working sync... I wasn't able to identify the process that triggers those events.

With `docker-sync` down, all IDE, browsers... `fswatch` was still reporting events.

**Comment by mickaelperrin** [comment] 2016-08-19 14:18
Some more debug informations here, I just discovered that my time machine backup was restarting from scratch (side effect of disabling / enabling).

I suspect that the process is busy copying other files at the moment... I suspect that if you have a time machine backup up to date, it will try to backup your files in real time, resulting in strange events that may confuse Unox / Unison. My backup will take several days to perform, I will update then...

**Comment by mickaelperrin** [comment] 2016-08-22 11:56
Some update here, my Time Machine backup is finished. And didn't get this issue so far... So it looks like it is not strictly related

**Comment by EugenMayer** [comment] 2016-08-22 12:07
So for now i are not specifically able to reproduce it, right?

**Comment by mickaelperrin** [comment] 2016-08-22 12:08
Yes, have no idea what was at the origin of this issue.

**Comment by EugenMayer** [comment] 2016-08-22 12:14
i suggest, closing this until it happens once again - then you might grasp any context you need

**Comment by mickaelperrin** [comment] 2016-08-23 08:27
Got the same issue this morning :( Dropbox was using a high amount of CPU, I suspect it was related. I killed Dropbox, this didn't stop the flood. Then I restarted the computer to stop it.

Note: My code and sync files are outside any Dropbox paths... crazy. Hope this is related only to my computer...

**Comment by EugenMayer** [comment] 2016-10-02 09:48
closing until any other notice / reproduction

**Closed by EugenMayer** 2016-10-02 09:48 UTC
Labels: bug, incomplete

**Comment by mickaelperrin** [comment] 2017-01-17 17:23
Some update, about this bug.

I experienced the same issue today while doing a rsync task...

I was rsyncing in ~/some/folder/project/src/www and the watcher was in ~/tmp/someproject/src.

Killing the rsync task, stopped the fs-events flood. Crazy...
