### ISSUE TITLE
After 0.4.2 update 'program:unison.command' contains names ('ENV_UNISON_ARGS') which cannot be expanded

### ISSUE THREAD

**Issue by chrisdlangton** [EugenMayer/docker-sync#367] opened 2017-05-08 01:25 UTC
### Error/Feature Requestion/Docs
Contianer log

```
user with uid 0 already exist and its root
/entrypoint.sh: ignoring /docker-entrypoint.d/*
doing initial sync with cp
chown ing file to uid 0
2017-05-08T01:15:22.518725644Z 
real	0m1.082s
user	0m0.000s
sys	0m0.090s
starting unison
/usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
Error: Format string 'unison %(ENV_UNISON_ARGS)s %(ENV_UNISON_EXCLUDES)s %(ENV_UNISON_SYNC_PREFER)s -numericids -repeat watch -auto -batch /host_sync /app_sync -logfile /tmp/unison.log' for 'program:unison.command' contains names ('ENV_UNISON_ARGS') which cannot be expanded. Available names: ENV_APP_VOLUME, ENV_HOME, ENV_HOSTNAME, ENV_HOST_VOLUME, ENV_LANG, ENV_OWNER, ENV_OWNER_HOMEDIR, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV_TZ, ENV_UNISON_DIR, ENV_UNISON_EXCLUDES, ENV_UNISON_SYNC_PREFER, group_name, here, host_node_name, process_num, program_name in section 'program:unison' (file: '/etc/supervisor.conf.d/supervisor.daemon.conf')
For help, use /usr/bin/supervisord -h
user with uid 0 already exist and its root
/entrypoint.sh: ignoring /docker-entrypoint.d/*
starting unison
/usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
Error: Format string 'unison %(ENV_UNISON_ARGS)s %(ENV_UNISON_EXCLUDES)s %(ENV_UNISON_SYNC_PREFER)s -numericids -repeat watch -auto -batch /host_sync /app_sync -logfile /tmp/unison.log' for 'program:unison.command' contains names ('ENV_UNISON_ARGS') which cannot be expanded. Available names: ENV_APP_VOLUME, ENV_HOME, ENV_HOSTNAME, ENV_HOST_VOLUME, ENV_LANG, ENV_OWNER, ENV_OWNER_HOMEDIR, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV_TZ, ENV_UNISON_DIR, ENV_UNISON_EXCLUDES, ENV_UNISON_SYNC_PREFER, group_name, here, host_node_name, process_num, program_name in section 'program:unison' (file: '/etc/supervisor.conf.d/supervisor.daemon.conf')
For help, use /usr/bin/supervisord -h
```

### Docker Driver
default? no vbox installed

### Sync strategy
default, containers created say `unison:hostsync`

### your docker-sync.yml

```
version: '2'
options:
  verbose: true
syncs:
  php-unison-sync:
    src: 'src/'
    sync_host_port: 10872
    sync_exclude_type: none
  php-unison-app-sync:
    src: 'app/'
    sync_host_port: 10873
    sync_exclude_type: none
  ui-unison-sync:
    src: 'src_ui/'
    sync_host_port: 10874
    sync_exclude_type: none
```

My compose files are using `:nocopy` for all 3 volumes as suggested when the upgrade took place.

### OS
macOS Sierra 10.12.4
Docker version 17.03.1-ce, build c6d412e

**Comment by chrisdlangton** [comment] 2017-05-08 01:27
@HengfengLi @ababushkin

**Comment by chrisdlangton** [comment] 2017-05-08 02:10
FYI
last known working state;
`gem uninstall docker-sync`
Choose to remove all versions.
`gem install docker-sync --version 0.3.9`

**Comment by mmrko** [comment] 2017-05-08 06:51
Same here.

**Comment by issei-m** [comment] 2017-05-08 07:29
Same issue here

**Comment by EugenMayer** [comment] 2017-05-08 08:36
my fault, sorry - it slipped through. I have to release 0.4.3 to fix this

**Comment by EugenMayer** [comment] 2017-05-08 08:38
sorry, please upgrade to 0.4.3, just published it

**Comment by chrisdlangton** [comment] 2017-05-08 08:39
:+1:

**Comment by ababushkin** [comment] 2017-05-15 00:02
Looks like this issue is happening again in docker-sync 0.4.5, which was released ~13 hours ago.

Just down graded to 0.4.4 and it works fine. Perhaps reopen this issue?

**Comment by EugenMayer** [comment] 2017-05-15 06:35
@ababushkin are you sure?

What is the exact error message? Might be related to https://github.com/EugenMayer/docker-sync/commit/6102649b4b080dbf0c8a7047a001dd49ede302d2

**Comment by ababushkin** [comment] 2017-05-15 11:28
@EugenMayer I'll double check on a separate workstation now and let you know.

**Comment by ababushkin** [comment] 2017-05-15 12:08
Also I realise this next question is outside the scope of this issue, but is there any useful guide on getting docker-sync to play nice with rvm?

I noticed when installing docker-sync via rvm it points to /usr/local/opt/ruby/bin/ruby, however rvm installs ruby in /usr/bin. For now I've symlinked ruby to that directory but it might help us non-ruby guys if there was something about this :)

**Comment by EugenMayer** [comment] 2017-05-15 15:56
@ababushkin please paste your docker-sync.yml file in a seperate issue, i close this one down, want to start from fresh here, not sure how to reproduce this ( since i cannot )

**Closed by EugenMayer** 2017-05-15 15:56 UTC
Labels: bug
