### ISSUE TITLE
Docker-sync not working after update (#2)

### ISSUE THREAD

**Issue by fredguile** [EugenMayer/docker-sync#539] opened 2018-03-12 14:15 UTC
Hi @EugenMayer,

Looks like I'm having this issue back with you last release (0.5.3).

### Error/Feature Requestion/Docs
```
 note:  You can also run docker-sync in the background with docker-sync start
          ok  Starting unison for sync coffeecirclelamp-sync
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' coffeecirclelamp-sync
       error  Error getting mapped port, exit code 137
     message  Template parsing error: template: :1:3: executing "" at <index (index .Networ...>: error calling index: index of untyped nil
```

### Docker Driver
d4m

### Sync strategy
unison

### your docker-sync.yml
```
version: '2'
options:
  verbose: false
  max_attempt: 15
syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  coffeecirclelamp-sync: #tip: add -sync and you keep consistent names als a convention
    notify_terminal: true
    src: './build'
    sync_excludes: ['var/cache/*','var/log/*','web/cache/*']
    sync_excludes_type: 'Path'
    sync_strategy: 'unison'
    sync_prefer: 'default'
    sync_userid: 2000
    sync_args: ['-perms=0']
    sync_host_ip: '127.0.0.1'
    watch_args: '-v'
```
### OS
OSX 10.13.3

Any clue? Thanks a lot!

**Comment by EugenMayer** [comment] 2018-03-12 14:16
dupe of https://github.com/EugenMayer/docker-sync/issues/537

**Closed by EugenMayer** 2018-03-12 14:16 UTC

**Comment by fredguile** [comment] 2018-03-12 14:20
okay, sorry! Not the same description however...

**Comment by EugenMayer** [comment] 2018-03-12 14:21
Well, max:attempts, 100% the same symptom :)

**Comment by fredguile** [comment] 2018-03-12 14:27
Yeah agree! But I forgot to mention my last attempts to solve the problem ;) so:
- moved from D4M edge channel to stable (17.12.0-ce) => didn't work
- reverted to docker-sync 0.5.2 => hmm nope
- okay, getting an older version of `eugenemayer/unison`? `docker pull eugenmayer/unison:hostsync_0.2` => hmm nope

If by any chance you have ideas? Still failing on this `Template parsing error: template: :1:3: executing "" at <index (index .Networ...>: error calling index: index of untyped nil`

**Comment by EugenMayer** [comment] 2018-03-12 14:30
check your ~/.docker-sync-global.yml and check if you have odd values there.

Other then that, i have no clue and it rather looks like parsing docker inspect is broken `.Networ` indicates that.

You might have not properly dowgraded DWm or whatever

**Comment by fredguile** [comment] 2018-03-12 14:36
You're right, actually I'm struggling downgrading to 0.5.2....

**Comment by EugenMayer** [comment] 2018-03-12 14:37
gem uninstall dwm
gem install dwm -v 0.5.2

**Comment by fredguile** [comment] 2018-03-12 14:43
Okay got it working, thanks! No idea why, but I had to run these commands several times before I indeed got version 0.5.2 seated into `/usr/local/bin/docker-sync`...
