### ISSUE TITLE
Error Updating to Newer Versions

### ISSUE THREAD

**Issue by zlr35** [EugenMayer/docker-sync#762] opened 2021-01-11 00:39 UTC
### Error
```
$ docker-sync start
     warning  There is an update (0.5.14) available (current version 0.0.11
). Please update before you continue
Shall i update docker-sync to 0.5.14 for you? Y
Updating installed gems
Updating docker-sync
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
     success  Successfully updated, please restart docker-sync and check the changelog at https://github.com/EugenMayer/docker-sync/wiki/5.-Changelog
```

### OS
Ubuntu 20.04

`gem` installs 0.0.11 and any attempt to install a later version gives:
```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
```

After adding `require 'date'` to `lib/config.rb` `docker-sync start` will actually run but gives the above update error. Despite saying successfully updated, it hasn't updated.

**Comment by omares** [comment] 2021-01-19 13:51
Hey, I was running into the same issue, luckily bundler provided more information.

In my case I had ruby 3 installed but the Gem expects version 2.x. Installing ruby 2.7.5 and doing the install procedure, fixed the issue for me.

No concrete idea why version 0.0.11 is installed with ruby 3 .Guess there is no ruby version limitation on that release.

```
bundle install
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby x86_64-darwin-20

    docker-sync (~> 0.5.14) x86_64-darwin-20 was resolved to 0.5.14, which depends on
      docker-compose (>= 1.1.7, ~> 1.1) x86_64-darwin-20 was resolved to 1.1.12, which depends on
        Ruby (~> 2.0) x86_64-darwin-20

    docker-sync (~> 0.5.14) x86_64-darwin-20 was resolved to 0.5.14, which depends on
      Ruby (>= 2.0) x86_64-darwin-20
❯ ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
```

**Comment by EugenMayer** [comment] 2021-04-30 06:09
fairly outdated version with 0.0.11 which does not play nice with the then used ruby. Closing this one since it is fairly unrelated for today

**Closed by EugenMayer** 2021-04-30 06:09 UTC

**Comment by pnbecker** [comment] 2021-04-30 08:59
@EugenMayer There is no problem with this specific version, the problem is that python-3-pip on macOS-Homebrew, Ubuntu and probably many other systems installs this old version by default. Getting this old version, not being able to update to a new one makes it unusable. Can you please reopen this issue and investigate? I'm happy to help as good as I can.

**Comment by EugenMayer** [comment] 2021-04-30 09:03
we already have 2 very unrelated issues here with very different causes. Could you please open a new dedicated @pnbecker. Thanks

**Comment by pnbecker** [comment] 2021-04-30 09:22
@EugenMayer of course. Thank you for taking this serious. #766
