### ISSUE TITLE
Documentation could be better

### ISSUE THREAD

**Issue by dimaqq** [EugenMayer/docker-sync#655] opened 2019-03-27 09:43 UTC
### Docs

https://docker-sync.readthedocs.io/en/latest/getting-started/configuration.html is almost impossible to read:
* lines in the config sample (reference section) are longer than rtd layout allows
* there are just too many options

Perhaps there could be 2 beginner examples — one for OSX and one for Win?

**Comment by EugenMayer** [comment] 2019-03-27 13:00
dupe of https://github.com/EugenMayer/docker-sync/issues/39 - @dimaqq jump the gun and help us improving it? any PRs are welcome

**Closed by EugenMayer** 2019-03-27 13:00 UTC
