### ISSUE TITLE
[WSL2] Not sync

### ISSUE THREAD

**Issue by chiqui3d** [EugenMayer/docker-sync#704] opened 2019-12-11 12:22 UTC
### Error/Feature Requestion/Docs
It does not synchronize, only sometimes and when it does it usually takes more than a minute to discover the change.

### Note

I have followed all the steps detailed in this section https://docker-sync.readthedocs.io/en/latest/getting-started/installation.html#let-s-go

### Version
0.5.14

### Sync strategy + version
unison version 2.51.2 (ocaml 4.08.1)

### OS
Windows 10 + WSL2 with Ubuntu and Docker

### Project

Symfony + PHP + Nginx

https://github.com/chiqui3d/symfony-docker

### commands I use
```
docker-sync start
docker-compose -f docker-compose-dev.yml up -d
```

### docker-sync

```yaml
options:
  compose-file-path: './docker-compose-dev.yml'
  verbose: true

version: '2'
syncs:
  app-sync:
    src: './app'
    sync_strategy: 'unison' # for osx use 'native_osx', for windows use 'unison'
    sync_host_ip: '127.0.0.1' #host ip isn't properly inferred
    sync_args:
      - '-perms=0'
      - "-ignore='Path .idea'"          # no need to send PHPStorm config to container
      - "-ignore='Path .git'"           # ignore the main .git repo
      - "-ignore='BelowPath .git'"      # also ignore .git repos in subfolders such as in composer vendor dirs
      - "-ignore='Path bin/*'"           # ignore the main .git repo
      - "-ignore='Path var/cache/*'"    # don't share the cache
      - "-ignore='Path var/sessions/*'" # we don't need the sessions locally
      - "-ignore='Path node_modules/*'" # remove this if you need code completion
      - "-ignore='Path vendor/*'"     # we could ignore the composer vendor folder, but then you won't have code completion in your IDE
```

### Terminal Screenshot

Part 1:
![docker-sync-console-1](https://user-images.githubusercontent.com/2461400/70620754-5a6b5d80-1c18-11ea-948d-9cb889a53654.png)
Part 2:
![docker-sync-console-2](https://user-images.githubusercontent.com/2461400/70620760-60f9d500-1c18-11ea-9b45-e1fa85f0233e.png)

**Comment by MantisMan13** [comment] 2020-02-08 20:35
Did you ever work this out? I'm looking at the question of getting this setup and going with WSL as per the project instructions or trying to jump into the Window Insider Slow track and get WSL2 where normal direct Docker Volumes are supposed to work just as well as native Linux ones. If you are on the pre-release of WSL2 and have you had slow sync issues doing the simple Volume setup in your docker-compose.yml?

**Comment by EugenMayer** [comment] 2020-02-09 07:34
WSL2 ist not even in the same Galaxy in terms of volume speed then you would have in Linux, AFAIR

**Comment by chiqui3d** [comment] 2020-02-10 06:17
@MantisMan13 I didn't solve it, I'm synchronizing from Windows to Docker with the Deployment option in PHPStorm IDE, and the truth is that I'm very happy, with WSL2 and Docker Edge,a little bit of a mess at first but everything is going very well.

**Comment by EugenMayer** [comment] 2020-02-10 06:31
I think IJ deployment options are a fairly good fit for on-demand synchronization. There are a couple of downsides, which are, at some way also upsides

1. deployment is using `rsync`, so it is like our rsync strategy` with one specific change, it does not use a file-system watcher ( which is the one getting stuck / bloated / slow ) but uses IDE "onSave/change" handlers which do only watch the files you are editing.

2. You have a nice diff-gui and can push force the changes if you like

When i would rate those, there is some kind of trade off:

For 1. is pretty neat and efficient, more then the fsevents watcher we use. On the other side, it is not generic and would become error prone if you change files outside the IDE, be it `git pull` on the shell or some kind of `sass` builder and so on. The developer must be much more aware and trigger the deployment manually if needed - this is a burden but probably one which one can take ( it make sense for me ).

Of course this is for people only which use IntelliJ, even though others have deployment options too, IJ is really far superior.


---

To WSL2 - it is basically the same issue as WSL or macOS. You have a virtualized linux kernel and a split file-system, which then get's synced - so there is a sync between "windows filesystem" and "linux filesystem" - that is what makes it slow and clunky and falsy ( the same issue as you have with macOS ). 

While WSL2 uses a little different tech then WSL1, it is still far worse in my benchmarks then the OSXFS "sync" implementation - all 3 are though miles away from native sync under Linux.

Considering the time Docker is on the market and the issue is known ( about 3 years ) and absolutely 0 movement / improvement has been made, including the big players like VMware failing on this issue too, i consider this rather very low level conceptual issue as "frozen". It makes sense for people to find either long term solutions to workaround or even switch to Linux if docker development becomes one of the main topics of the day.

**Comment by EugenMayer** [comment] 2020-04-09 05:40
Closing this issues since it is stalled / solved

**Closed by EugenMayer** 2020-04-09 05:40 UTC

**Comment by tlieschenfon** [comment] 2020-04-26 20:36
Just one comment from my side for those being redirected to this issue report by Google search (like me). As you are able to run WSL1 and WSL2 distributions parallely, there's still the option to use Docker WSL Backend with WSL2 while running docker-sync in any WSL1 installation.

After playing around a while this solution turned out to be the best one for me - I'm using shell scripts every now and then for git pulls but I don't like to care about deploying stuff manually.
