### ISSUE TITLE
docker-sync-stack start not syncing (0.4.0)

### ISSUE THREAD

**Issue by ad-on-is** [EugenMayer/docker-sync#340] opened 2017-05-05 10:22 UTC
Hi, 
I updated docker-sync to 0.4.0 and the sync somehow stopped working.
When I ssh into the nginx-container the files from my host are not synced to `nginx:/usr/share/nginx/html` as they are supposed to, though they are synced in `web-sync:/host_sync` container. The `web-sync:/app_sync`contains files (index.html, 50x.html) from the nginx-container.

Can someone tell me please, what I'm missing here?

Cheers,
Adis

Here's my configuration.

docker-compose-dev.yml

```
version: '2'
services:
  nginx:
    volumes:
      - web-sync:/usr/share/nginx/html/:rw
  php:
    volumes:
      - web-sync:/usr/share/nginx/html/:rw
volumes:
    web-sync:
      external: true
```
docker-sync.yml

```
version: '2'
options:
  verbose: true
syncs:
  web-sync:
    src: '/Users/add/Projects/Web'
    sync_excludes: ['Docker', 'Archive', '.sass-cache/', 'sass/', 'sass-cache/', 'bower_components/', 'node_modules/', '.gitignore', '.git/', '.svn/', '*.coffee', '*.scss', '*.sass']
    watch_excludes: ['Docker', 'Archive', '.*/.git', '.*/node_modules', '.*/bower_components', '.*/sass-cache', '.*/.sass-cache', '.*/.sass-cache', '.coffee', '.scss', '.sass', '.gitignore']
```

verbose-output

```
note:  You can also run docker-sync in the background with docker-sync --daemon
          ok  Starting native_osx
          ok  web-sync container not running
          ok  creating web-sync container
     command  docker run -v web-sync:/app_sync -v /Users/add/Projects/Web:/host_sync -e VOLUME=/sync -e TZ=${TZ-`readlink /etc/localtime | sed -e 's,/usr/share/zoneinfo/,,'`} -e UNISON_EXCLUDES="-ignore='Name Docker' -ignore='Name Archive' -ignore='Name .sass-cache/' -ignore='Name sass/' -ignore='Name sass-cache/' -ignore='Name bower_components/' -ignore='Name node_modules/' -ignore='Name .gitignore' -ignore='Name .git/' -ignore='Name .svn/' -ignore='Name *.coffee' -ignore='Name *.scss' -ignore='Name *.sass'" -e UNISON_SYNC_PREFER="-prefer /host_sync"  --name web-sync -d eugenmayer/unison:hostsync
          ok  starting initial sync of web-sync
     success  Sync container started
     success  Watcher disabled by configuration
          ok  Found implicit docker-compose-dev.yml and using it from /Volumes/add/Projects/Web/Docker/docker-compose-dev.yml
          ok  starting compose
```

**Comment by EugenMayer** [comment] 2017-05-05 10:37
please remove watch excludes, not needed anymore.

while you started the sync, do a docker ps, find the sync container, `docker exec -it <syncontainer> sh` into it

- now look at /host_sync .. those should be the files from your src folder - all there?
- now look at /app_sync .. those are the files locally synced by unison - all there?

If that is all in place, report back here, if not, please check /var/log/unison.log on the sync container, what does it say? also what does `supervisorctl status` tell you

**Comment by ad-on-is** [comment] 2017-05-05 10:58
> now look at /host_sync .. those should be the files from your src folder - all there?
yep, all there

> now look at /app_sync .. those are the files locally synced by unison - all there?
what do you mean by that? this folders contain the files, that are located in the nginx-container under /usr/share/nginx/html

My problem is that I want my nginx-container:/usr/share/nginx/html to contain the files/folders from sync-container:/host_sync

```
bash-4.3# supervisorctl status
unison                           RUNNING   pid 18, uptime 0:04:33
```

**Comment by Benoth** [comment] 2017-05-05 11:00
Hi,

I have the exact same issue, 

- /host_sync is ok
- /app_sync is empty
- supervisorctl status : unison RUNNING   pid 38, uptime 0:00:13
- /var/log/unison.log does not exist

Maybe this can be of any help ?
```
/tmp # ls -al
total 296
drwxrwxrwt    1 root     root          4096 May  5 12:51 .
drwxr-xr-x    1 root     root          4096 May  5 12:51 ..
srwx------    1 root     root             0 May  5 12:51 supervisor.sock
-rw-r--r--    1 root     root          1213 May  5 12:53 supervisord.log
-rw-r--r--    1 root     root             2 May  5 12:51 supervisord.pid
-rw-------    1 root     root        283378 May  5 12:53 unison-stdout---supervisor-pnMQFj.log

/tmp # cat *.log
2017-05-05 12:51:51,141 CRIT Supervisor running as root (no user in config file)
2017-05-05 12:51:51,141 WARN Included extra file "/etc/supervisor.conf.d/supervisor.daemon.conf" during parsing
2017-05-05 12:51:51,150 INFO RPC interface 'supervisor' initialized
2017-05-05 12:51:51,150 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-05-05 12:51:51,150 INFO supervisord started with pid 1
2017-05-05 12:51:52,153 INFO spawned: 'unison' with pid 24
2017-05-05 12:51:53,184 INFO success: unison entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-05-05 12:53:30,317 INFO exited: unison (exit status 2; expected)
2017-05-05 12:53:30,320 INFO spawned: 'unison' with pid 38
2017-05-05 12:53:30,321 INFO reaped unknown pid 25
2017-05-05 12:53:31,321 INFO success: unison entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-05-05 12:53:52,513 INFO exited: unison (exit status 2; expected)
2017-05-05 12:53:52,513 INFO reaped unknown pid 39
2017-05-05 12:53:53,519 INFO spawned: 'unison' with pid 41
2017-05-05 12:53:54,535 INFO success: unison entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Contacting server...
Looking for changes
Warning: No archive files were found for these roots, whose canonical names are:
	/host_sync
	/app_sync
This can happen either
because this is the first time you have synchronized these roots,
or because you have upgraded Unison to a new version with a different
archive format.

Update detection may take a while on this run if the replicas are
large.

Unison will assume that the 'last synchronized state' of both replicas
was completely empty.  This means that any files that are different
will be reported as conflicts, and any files that exist only on one
replica will be judged as new and propagated to the other replica.
If the two replicas are identical, then no changes will be reported.

If you see this message repeatedly, it may be because one of your machines
is getting its address from DHCP, which is causing its host name to change
between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
environment variable for advice on how to correct this.

Donations to the Unison project are gratefully accepted:
http://www.cis.upenn.edu/~bcpierce/unison

Reconciling changes
file     ---->            .env
file     ---->            .env.example
dir      ---->            app
file     ---->            artisan
dir      ---->            bootstrap
file     ---->            codeception.yml
file     ---->            composer
file     ---->            composer.json
file     ---->            composer.lock
dir      ---->            config
dir      ---->            database
file     ---->            docker-compose.yml
file     ---->            docker-sync.yml
file     ---->            gulpfile.js
dir      ---->            migration
file     ---->            package.json
file     ---->            phpspec.yml
file     ---->            phpunit.xml
dir      ---->            public
file     ---->            readme.md
dir      ---->            resources
file     ---->            server.php
dir      ---->            storage
dir      ---->            tests
dir      ---->            vendor
Propagating updates
UNISON 2.48.4 started propagating changes at 12:53:30.31 on 05 May 2017
Fatal error: Error in getLogch:
/var/log/unison.log: Permission denied
Fatal error: exception Util.Fatal("Error in getLogch:\n/var/log/unison.log: Permission denied")
Raised at file "/tmp/unison-2.48.4/src/ubase/util.ml", line 199, characters 6-17
Called from file "/tmp/unison-2.48.4/src/ubase/trace.ml", line 153, characters 13-23
Called from file "/tmp/unison-2.48.4/src/uitext.ml", line 826, characters 2-24
Called from file "/tmp/unison-2.48.4/src/uitext.ml", line 889, characters 6-23
Called from file "/tmp/unison-2.48.4/src/main.ml", line 241, characters 2-257
Called from file "/tmp/unison-2.48.4/src/linktext.ml", line 19, characters 18-40
Contacting server...
Looking for changes
Reconciling changes
file     ---->            .env
file     ---->            .env.example
dir      ---->            app
file     ---->            artisan
dir      ---->            bootstrap
file     ---->            codeception.yml
file     ---->            composer
file     ---->            composer.json
file     ---->            composer.lock
dir      ---->            config
dir      ---->            database
file     ---->            docker-compose.yml
file     ---->            docker-sync.yml
file     ---->            gulpfile.js
dir      ---->            migration
file     ---->            package.json
file     ---->            phpspec.yml
file     ---->            phpunit.xml
dir      ---->            public
file     ---->            readme.md
dir      ---->            resources
file     ---->            server.php
dir      ---->            storage
dir      ---->            tests
dir      ---->            vendor
Propagating updates
UNISON 2.48.4 started propagating changes at 12:53:52.50 on 05 May 2017
Fatal error: Error in getLogch:
/var/log/unison.log: Permission denied
Fatal error: exception Util.Fatal("Error in getLogch:\n/var/log/unison.log: Permission denied")
Raised at file "/tmp/unison-2.48.4/src/ubase/util.ml", line 199, characters 6-17
Called from file "/tmp/unison-2.48.4/src/ubase/trace.ml", line 153, characters 13-23
Called from file "/tmp/unison-2.48.4/src/uitext.ml", line 826, characters 2-24
Called from file "/tmp/unison-2.48.4/src/uitext.ml", line 889, characters 6-23
Called from file "/tmp/unison-2.48.4/src/main.ml", line 241, characters 2-257
Called from file "/tmp/unison-2.48.4/src/linktext.ml", line 19, characters 18-40
Contacting server...
Looking for changes
| vendor/fzaninotto/faker/src/Faker/Provider/es_AR/PhoneNumber.php
```

**Comment by EugenMayer** [comment] 2017-05-05 11:01
```
Fatal error: Error in getLogch:
/var/log/unison.log: Permission denied
```

I guess you both have a sync-user set, right?

**Comment by Benoth** [comment] 2017-05-05 11:05
You're right for me :

```
version: "2"

options:
  verbose: true

syncs:
  myproject-sync:
    src: './'
    sync_userid: '33'
    sync_excludes:
      - .docker
      - .git
```

**Comment by EugenMayer** [comment] 2017-05-05 11:07
@Benoth https://github.com/EugenMayer/docker-sync/issues/343

**Comment by ad-on-is** [comment] 2017-05-05 11:13
Unfortunately adding sync_userid: '33' didn't work for me.

**Comment by EugenMayer** [comment] 2017-05-05 11:14
please read the issues, not just act :) - you shall not set it, if you do not need it. Your issue is different then @Benoth issue is most probably.

Your problem though is, you did not do what i ask you for, but he did without being asked. So why you just dont join him :)

**Comment by ad-on-is** [comment] 2017-05-05 11:25
If you could be more specific, I could provide you all the information you need ;-) But asking for a log-file that isn't even there doesn't help anyone. You even asked if we BOTH have sync-user set, so ... but nevermind... 

so, /tmp/supervisord.log

```
2017-05-05 13:20:32,964 CRIT Supervisor running as root (no user in config file)
2017-05-05 13:20:32,964 WARN Included extra file "/etc/supervisor.conf.d/supervisor.daemon.conf" during parsing
2017-05-05 13:20:32,973 INFO RPC interface 'supervisor' initialized
2017-05-05 13:20:32,973 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-05-05 13:20:32,973 INFO supervisord started with pid 1
2017-05-05 13:20:33,978 INFO spawned: 'unison' with pid 19
2017-05-05 13:20:34,979 INFO success: unison entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

/tmp/unison-stdout....log

```
Contacting server...
Looking for changes
Warning: No archive files were found for these roots, whose canonical names are:
	/host_sync
	/app_sync
This can happen either
because this is the first time you have synchronized these roots, 
or because you have upgraded Unison to a new version with a different
archive format.  

Update detection may take a while on this run if the replicas are 
large.

Unison will assume that the 'last synchronized state' of both replicas
was completely empty.  This means that any files that are different
will be reported as conflicts, and any files that exist only on one
replica will be judged as new and propagated to the other replica.
If the two replicas are identical, then no changes will be reported.

If you see this message repeatedly, it may be because one of your machines
is getting its address from DHCP, which is causing its host name to change
between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
environment variable for advice on how to correct this.

Donations to the Unison project are gratefully accepted: 
http://www.cis.upenn.edu/~bcpierce/unison

- ._.DS_Store
/ and all my
| other files
/ and folders
/ ...
```

**Comment by EugenMayer** [comment] 2017-05-05 11:27
please `supervisorctl status`

**Comment by EugenMayer** [comment] 2017-05-05 11:29
@ad-on-is was this folder pre-pupulated in the image? (with files)

**Comment by ad-on-is** [comment] 2017-05-05 11:29
Already provided that info to you, right after you asked for it: https://github.com/EugenMayer/docker-sync/issues/340#issuecomment-299436690

But here again:

```
bash-4.3# supervisorctl status
unison                           RUNNING   pid 19, uptime 0:08:43
```

**Comment by ad-on-is** [comment] 2017-05-05 11:31
> was this folder pre-pupulated in the image? (with files)

if you mean, weather the app_sync folder is populated with files that were pre-populated by the nginx-image, then yes

**Comment by EugenMayer** [comment] 2017-05-05 11:42
@ad-on-is sorry skipped the supervisorctl info. 

I have to look into your issue more deeply. I think i have a smell already

**Comment by ad-on-is** [comment] 2017-05-05 11:44
No problem, buddy - "Freitog is!" :D

**but wait... now it's working!** - app_sync contains now the files of host_sync.

Can it be, that it just took a while?

**Comment by EugenMayer** [comment] 2017-05-05 11:46
How large is your codebase?

Please install docker-sync 0.4.1-beta1

```
gem uninstall docker-sync
gem install docker-sync --version 0.4.1-beta1
docker-sync clean
docker-sync start
```

**Comment by ad-on-is** [comment] 2017-05-05 11:52
I have a large codebase, but it worked until 0.2.0 fine. When executing docker-sync-stack start I could see how long it took to sync and when it finished. But with 0.4.0 it synced really fast, and I thought it was because of new native_osx.

Getting error when trying to install, even with sudo:
```
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
    Illformed requirement ["0.4.1-beta1"]
```

**Comment by EugenMayer** [comment] 2017-05-05 11:53
hmm ist actually there https://rubygems.org/gems/docker-sync/versions/0.4.1.pre.beta1

```
gem install docker-sync --version 0.4.1-beta1                                                            137 ↵
Fetching: docker-sync-0.4.1.pre.beta1.gem (100%)
Successfully installed docker-sync-0.4.1.pre.beta1
1 gem installed
```

**Comment by ad-on-is** [comment] 2017-05-05 12:01
`gem install docker-sync --pre`did the trick

**Comment by ad-on-is** [comment] 2017-05-05 12:02
Actually did not:

```
AdisMBP:Docker add$ docker-sync-stack start
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb:191:in `initialize': Malformed version number string 0.4.1-beta1 (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.1.pre.beta1/lib/docker-sync/upgrade_check.rb:31:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.1.pre.beta1/lib/docker-sync/upgrade_check.rb:31:in `should_run'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.1.pre.beta1/lib/docker-sync/upgrade_check.rb:13:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.1.pre.beta1/tasks/stack/stack.thor:28:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.1.pre.beta1/bin/docker-sync-stack:15:in `<top (required)>'
	from /usr/local/bin/docker-sync-stack:23:in `load'
	from /usr/local/bin/docker-sync-stack:23:in `<main>'
```

**Comment by EugenMayer** [comment] 2017-05-05 12:07
to the issue above: well seems like the version-thingy does not work for the system ruby, it cannot handle betas - you better downgrade for now

anyway, beta-1 does not fix it for you, i could reproduce the cause.

**Comment by ad-on-is** [comment] 2017-05-05 12:12
glad you could reproduce, where was my mistake?

**Comment by EugenMayer** [comment] 2017-05-05 12:23
Not yours, its a combination of double-volume mounts. Hard to explain right now, when i have a fix, i  will try to explain it

**Comment by EugenMayer** [comment] 2017-05-05 12:40
ok so clean your docker-compose / docker-sync stack

and adjust your -dev compose file to use nocopy:

  - dwcode-sync:/var/www:nocopy

This is important, since otherwise, if the destination mount has been declared as a volume during container build, its content will be copied to dwcode-sync, thus merged with our host source - which is not what we want, we want to run the container on the codebase of the host initially

I will add this to the docs

**Comment by EugenMayer** [comment] 2017-05-05 12:47
Happy developing :)

**Closed by EugenMayer** 2017-05-05 12:47 UTC
