### ISSUE TITLE
docker-sync does not start after docker engine restart.

### ISSUE THREAD

**Issue by Fulkman** [EugenMayer/docker-sync#768] opened 2021-05-19 11:12 UTC
### Error

With first run, everything working as expected.
```shell
docker-sync start
          ok  Starting native_osx for sync appcode-native-osx-sync
          ok  appcode-native-osx-sync container not running
          ok  creating appcode-native-osx-sync container
          ok  Starting precopy
     precopy  docker run --rm -v "appcode-native-osx-sync:/app_sync" -v "$HOME/workspace/docker-sync-boilerplate/default/app:/host_sync" -e HOST_VOLUME=/host_sync -e APP_VOLUME=/app_sync -e TZ=$(basename $(dirname `readlink /etc/localtime`))/$(basename `readlink /etc/localtime`) -e UNISON_SRC="/host_sync" -e UNISON_DEST="/app_sync" -e UNISON_ARGS=" -ignore='Name ignored_folder' -ignore='Name .ignored_dot_folder' -prefer /host_sync -numericids -auto -batch" -e UNISON_WATCH_ARGS="-repeat watch"  --name appcode-native-osx-sync eugenmayer/unison:2.51.3-4.12.0-AMD64 /usr/local/bin/precopy_appsync
doing initial sync with unison
Unison 2.51.3 (ocaml 4.12.0): Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.51.3 (OCAML 4.12.0) started propagating changes at 12:51:30.48 on 19 May 2021
[BGN] Copying index.html from /host_sync to /app_sync
[END] Copying index.html
UNISON 2.51.3 (OCAML 4.12.0) finished propagating changes at 12:51:30.48 on 19 May 2021
Saving synchronizer state
Synchronization complete at 12:51:30  (1 item transferred, 0 skipped, 0 failed)
real    0m 0.12s
user    0m 0.05s
sys     0m 0.01s
chown ing file to uid 0
initial sync done using unison
          ok  Starting container
     command  docker run -d -v "appcode-native-osx-sync:/app_sync" -v "$HOME/workspace/docker-sync-boilerplate/default/app:/host_sync" -e HOST_VOLUME=/host_sync -e APP_VOLUME=/app_sync -e TZ=$(basename $(dirname `readlink /etc/localtime`))/$(basename `readlink /etc/localtime`) -e UNISON_SRC="/host_sync" -e UNISON_DEST="/app_sync" -e UNISON_ARGS=" -ignore='Name ignored_folder' -ignore='Name .ignored_dot_folder' -prefer /host_sync -numericids -auto -batch" -e UNISON_WATCH_ARGS="-repeat watch"  --name appcode-native-osx-sync eugenmayer/unison:2.51.3-4.12.0-AMD64
9d3b3e2174f7ad8a37cf435c587b61ee32410deecc6fbf5c9622e5a2abdfb82d
          ok  starting initial sync of appcode-native-osx-sync
     success  Sync container started
     success  Starting Docker-Sync in the background
```
But after manually docker engine restart (Docker Desktop -> Restart - simulate computer reboot).
Second run end up with `supervisor` error.
```shell
docker-sync start
          ok  Starting native_osx for sync appcode-native-osx-sync
          ok  appcode-native-osx-sync container not running
          ok  starting appcode-native-osx-sync container
     command  docker start appcode-native-osx-sync && docker exec appcode-native-osx-sync supervisorctl restart unison
appcode-native-osx-sync
unix:///tmp/supervisor.sock no such file
Traceback (most recent call last):
        13: from $HOME/.gem/ruby/2.6.0/bin/docker-sync:23:in `<main>'
        12: from $HOME/.gem/ruby/2.6.0/bin/docker-sync:23:in `load'
        11: from $HOME/.gem/ruby/2.6.0/gems/docker-sync-0.6.0/bin/docker-sync:14:in `<top (required)>'
        10: from $HOME/.gem/ruby/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
         9: from $HOME/.gem/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
         8: from $HOME/.gem/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
         7: from $HOME/.gem/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
         6: from $HOME/.gem/ruby/2.6.0/gems/docker-sync-0.6.0/tasks/sync/sync.thor:47:in `start'
         5: from $HOME/.gem/ruby/2.6.0/gems/docker-sync-0.6.0/tasks/sync/sync.thor:181:in `daemonize'
         4: from $HOME/.gem/ruby/2.6.0/gems/docker-sync-0.6.0/lib/docker-sync/sync_manager.rb:102:in `start_container'
         3: from $HOME/.gem/ruby/2.6.0/gems/docker-sync-0.6.0/lib/docker-sync/sync_manager.rb:102:in `each'
         2: from $HOME/.gem/ruby/2.6.0/gems/docker-sync-0.6.0/lib/docker-sync/sync_manager.rb:103:in `block in start_container'
         1: from $HOME/.gem/ruby/2.6.0/gems/docker-sync-0.6.0/lib/docker-sync/sync_process.rb:105:in `start_container'
$HOME/.gem/ruby/2.6.0/gems/docker-sync-0.6.0/lib/docker-sync/sync_strategy/native_osx.rb:109:in `start_container': Start failed (RuntimeError)
```
However, for the third time, run everything as if nothing happened and everything works perfectly.
```shell
docker-sync start
          ok  Starting native_osx for sync appcode-native-osx-sync
          ok  appcode-native-osx-sync container still running, restarting unison in container
     command  docker exec appcode-native-osx-sync supervisorctl restart unison
unison: stopped
unison: started
          ok  starting initial sync of appcode-native-osx-sync
     success  Sync container started
     success  Starting Docker-Sync in the background
```

The problem is that the second start (after restarting the docker) ends with errors.
Currently to solve this "issue" I need to add a second run to make sure it works.

### Docker Driver
Docker Desktop Community 3.3.1 (63152)
Engine: 20.10.5
Compose: 1.19.0

### Sync strategy
`native_osx`

### boilerplate/default/docker-sync.yml
```yml
version: "2"

options:
  verbose: true
syncs:
  appcode-native-osx-sync: # tip: add -sync and you keep consistent names as a convention
    src: './app'
    # sync_strategy: 'native_osx' # not needed, this is the default now
    sync_excludes: ['ignored_folder', '.ignored_dot_folder']
```

### OS
macOS Big Sur (11.2.3)

**Comment by EugenMayer** [comment] 2021-05-19 13:56
Is this related to the new unison image / was it different for you before 0.0.6?

**Comment by Fulkman** [comment] 2021-05-19 14:50
Sorry, but I don't know how this behaves in previous versions. I'm fairly new to "dock sync".

**Comment by EugenMayer** [comment] 2021-05-19 14:53
You should not expect me to work on this tightly or at all. That is not a use case that is very usual and if you have a workaround it's fine.

If you plan to work on that yourself, I'm happy to review a PR anytime.

**Comment by pnbecker** [comment] 2021-06-04 19:43
I'm getting the same problem since I upgraded to docker-sync 0.6.0.  In 0.5.x I didn't had this issue. So yes, it probably has something to do with the changes in 0.6.0.

P.S. I don't expect anyone to work on this. I'm grateful for docker-sync as it is. I just thought I answer the question.

**Comment by dedene** [comment] 2021-06-28 14:29
I'm also seeing this behavior only recently. So I presume it is indeed related to the new docker-sync 0.6.0 or an update of Docker or a combination? I'm also on Big Sur 11.4 but I believe this only started recently.

**Comment by prebm** [comment] 2021-07-05 07:29
To add some observations:

- the issue exists both in 0.5.14 and 0.6.0
- the issue arises when the sync container is not running and started, maybe connected with the abovementioned
```
command  docker start appcode-native-osx-sync && docker exec appcode-native-osx-sync supervisorctl restart unison
```
- Docker 3.5.1.7, macOS Big Sur

**Comment by EugenMayer** [comment] 2022-05-06 06:22
Closing as non critical issue / feature and i'am not going to work and further nice to have features for now. Be sure to reopen this issue if you want to work on this issue yourself and provide a PR. Happy to review those

**Closed by EugenMayer** 2022-05-06 06:22 UTC
Labels: help wanted

**Comment by Housik** [comment] 2023-01-25 19:14
@EugenMayer This is caused by executing following commands at the same time with wrong assumption, that first command is fully completed (= supervisor service in appcode-native-osx-sync container is running), when executing second command. Unfortunately it is not running and execution of `supervisorctl restart unison` resulting to runtime error of `docker-sync` command.

This happens to me every time, when container is started for the first time. So any batch of commands having `docker-sync start` at the beginning is failing and must be run twice. Please try to resolve this issue, as it is pretty annoying.

When I execute commands separately via terminal

- docker start appcode-native-osx-sync
- docker exec appcode-native-osx-sync supervisorctl restart unison

everything works fine.

So simple but suboptimal solution is to add some delay between this two commands. Or somehow wait in loop until supervisor service in container is started.

**Comment by raghuiamsingh** [comment] 2023-03-27 07:44
try running
`docker-sync clean`

and then try starting
`docker-sync start`
