### ISSUE TITLE
unison-fsmonitor on Linux

### ISSUE THREAD

**Issue by Flyingmana** [EugenMayer/docker-sync#614] opened 2018-11-02 12:45 UTC
### Error/Feature Requestion/Docs
```
$ docker-sync start --no-daemon --foreground
       note:  Starting in foreground mode
sh: 1: brew: not found
     warning  Could not find eugenmayer/dockersync/unox. Trying to install it now.
Install eugenmayer/dockersync/unox for you? [y/N] y
     command  apt-get install -y eugenmayer/dockersync/unox
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package eugenmayer/dockersync
```

afterwards installing unison manually as suggested in the wiki to have unison-fsmonitor available.
Then trying again

```
 warning  You installed unison-fsmonitor (unox) the old legacy way (i.e. not using brew). We need to fix that.
Uninstall legacy unison-fsmonitor (unox)? (y/N) N
       error  webshop-sync has been configured to sync with unison, but no unison available
       error  Failed to remove legacy unison-fsmonitor (unox). Please delete /usr/local/bin/unison-fsmonitor manually and try again.
```

Is unison-fsmonitor not supported at all anymore? Can I somehow skip this step?

### Docker Driver
? (d4m or docker-machine+vbox/fusion)

### Sync strategy
? (unison)

### your docker-sync.yml

is this relevant for this kind of error?

### OS
Linux (Ubuntu)

**Comment by EugenMayer** [comment] 2018-11-02 14:01
dupe of https://github.com/EugenMayer/docker-sync/issues/609

**Closed by EugenMayer** 2018-11-02 14:01 UTC
