### ISSUE TITLE
Add visual feedback or a message stating that first sync can take some minutes to complete.

### ISSUE THREAD

**Issue by rodrigoaguilera** [EugenMayer/docker-sync#568] opened 2018-04-05 08:28 UTC
### Feature Request
I am faced with users that are confused by the time it takes to do the first sync so they stop docker-sync and run it again before the process completes.

I was wondering if its possible to add some kind "progress feedback" like printing 3 dots every 10 seconds or a message that gives some information about what is about to happen.

### Docker Driver
d4m 

### Sync strategy
native_osx

### OS
OSX 10.13

**Comment by EugenMayer** [comment] 2018-04-05 08:49
Sure, sounds good. Are you in it for a PR? :)

**Comment by rodrigoaguilera** [comment] 2018-04-05 11:27
I don't know much about ruby but I think I understand the architecture of docker sync.
Maybe if you keep open this issue for a month or so I can give it a try.

Thank you for the encouragement 🙂

**Comment by torreytsui** [comment] 2018-04-06 08:00
@rodrigoaguilera I just happened to come across and wonder if this information can help you a bit in the PR.

This may be the place to look at
https://github.com/EugenMayer/docker-image-unison/blob/master/precopy_appsync.sh#L10

Looks like the simplest way is doing something like this:

```diff
- time ruby -e '`unison #{ENV["UNISON_ARGS"]} #{ENV["UNISON_SYNC_PREFER"]} #{ENV["UNISON_EXCLUDES"]} -numericids -auto -batch /host_sync /app_sync`'
+ time ruby -e '`unison #{ENV["UNISON_ARGS"]} #{ENV["UNISON_SYNC_PREFER"]} #{ENV["UNISON_EXCLUDES"]} -numericids -auto -batch /host_sync /app_sync -logfile /tmp/unison.log`'
```

**Comment by shanempope** [comment] 2018-04-17 19:37
I believe the issue is in unison, not docker-sync. The line "Looking for changes" is what takes the most time for me:
https://github.com/bcpierce00/unison/blob/1da5309d455e39de2516e976af3edffa081a3005/src/uitext.ml#L966

**Comment by EugenMayer** [comment] 2018-07-22 04:43
closing this due to no progress. reopen anytime when you want to continue working on this

**Closed by EugenMayer** 2018-07-22 04:43 UTC
