### ISSUE TITLE
0.4.5 seems broken on Mac

### ISSUE THREAD

**Issue by YouriT** [EugenMayer/docker-sync#393] opened 2017-05-15 09:46 UTC
### Error
Just installed 0.4.5 and there is no sync happening anymore. Had to revert to `v0.4.4` to get it working again.
So I start with: `docker-sync-stack start`
Alter a file within `src`
Nothing happens
When `docker exec -ti container ash` cat-ing the modified file reflects old version of the file.
Even between starts in doesn't synchronise, I've to delete the volume to get latest version of modified files.

### Docker Driver
Docker version 17.03.1-ce, build c6d412e

### Sync strategy
`native_osx`

### docker-sync.yml
```
version: "2"
options:
  verbose: true
syncs:
  broker-sync:
    src: './src'
    sync_excludes: ['build', 'coverage', '.git', '.idea']
```

### OS
`10.12.4`

### Additional logs of 0.4.5 start
```
$ docker-sync-stack start
       note:  You can also run docker-sync in the background with docker-sync --daemon
          ok  Starting native_osx for sync broker-sync
          ok  broker-sync container not running
          ok  creating broker-sync container
          ok  Starting precopy
Contacting server...
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.48.4 started propagating changes at 11:34:03.74 on 15 May 2017
[BGN] Copying .DS_Store from /host_sync to /app_sync
[END] Copying .DS_Store
[BGN] Copying app.ts from /host_sync to /app_sync
[END] Copying app.ts
[BGN] Copying config.ts from /host_sync to /app_sync
[END] Copying config.ts
[BGN] Copying controllers from /host_sync to /app_sync
[END] Copying controllers
[BGN] Copying lib from /host_sync to /app_sync
[END] Copying lib
[BGN] Copying models from /host_sync to /app_sync
[END] Copying models
[BGN] Copying routes from /host_sync to /app_sync
[END] Copying routes
[BGN] Copying tests from /host_sync to /app_sync
[END] Copying tests
UNISON 2.48.4 finished propagating changes at 11:34:04.03 on 15 May 2017
Saving synchronizer state
Synchronization complete at 11:34:04  (8 items transferred, 0 skipped, 0 failed)
real	0m 0.91s
user	0m 0.07s
sys	0m 0.09s
          ok  Starting container
     command  docker run -d -v broker-sync:/app_sync -v /Users/Youri/broker/src:/host_sync -e HOST_VOLUME=/host_sync -e APP_VOLUME=/app_sync -e TZ=${TZ-`readlink /etc/localtime | sed -e 's,/usr/share/zoneinfo/,,'`} -e UNISON_EXCLUDES="-ignore='Name build' -ignore='Name coverage' -ignore='Name .git' -ignore='Name .idea'" -e UNISON_SYNC_PREFER="-prefer /host_sync"  --name broker-sync eugenmayer/unison:hostsync_0.2
          ok  starting initial sync of broker-sync
     success  Sync container started
     success  Showing unison logs from your sync container: broker-sync
          ok  starting compose
```

**Comment by ababushkin** [comment] 2017-05-15 12:11
This is a duplicate of https://github.com/EugenMayer/docker-sync/issues/367

For now I recommend you uninstall docker-sync ```gem uninstall docker-sync``` and install version 0.4.4 ```gem install docker-sync --version 0.4.4``` @EugenMayer will have a patch ready soon I imagine 👍

**Comment by staskrak** [comment] 2017-05-15 12:47
Same problem with 0.4.5. Come back to 0.4.4 - everything perfectly!

**Comment by EugenMayer** [comment] 2017-05-15 15:56
looking into this just right now, thank you for reporting this

**Comment by EugenMayer** [comment] 2017-05-15 16:05
solve, sorry! regression bug

**Closed by EugenMayer** 2017-05-15 16:05 UTC
