### ISSUE TITLE
Blocking until all changes have been written.

### ISSUE THREAD

**Issue by thesamet** [EugenMayer/docker-sync#360] opened 2017-05-07 05:37 UTC
### Error/Feature Requestion/Docs
In my workflow I am editing files on the host, saving them, and running a docker container that mounts the synchronized named volume and runs tests in it.

Is there a way to tell that all the locally saved changes have been committed to the named volume? Ideally, the test script have a way to block until everything is synced to prevent the tests running off stale sources. This is especially important during the initial sync which can be very slow.

### Docker Driver
docker for mac

### Sync strategy
default

**Comment by EugenMayer** [comment] 2017-05-07 08:59
dupe of https://github.com/EugenMayer/docker-sync/issues/357

**Closed by EugenMayer** 2017-05-07 08:59 UTC
