### ISSUE TITLE
Formalize and document linux support

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-sync#386] opened 2017-05-11 20:06 UTC
- How to setup docker-sync on linux
- what is needed
- what is not supported
- clues
- does daemon mode work? 
- does -stack work?
- low prio: https://github.com/EugenMayer/docker-sync/wiki/4.-Performance ( just to be able to compare )
- Why even do that / motivation, written something here https://github.com/EugenMayer/docker-sync/wiki/8.-Strategies#native_linux .. since you are actually the domain master here, rewrite it, put it on the linux installation/configuration page :)

@ignatiusreza thats your masterpiece right, lets tie it together. I will then also update the project page that we slowly have windows and linux support ( beta ).

Could you wrap this up in a Wiki Page https://github.com/EugenMayer/docker-sync/wiki/docker-sync-on-Linux

We have this for windows https://github.com/EugenMayer/docker-sync/wiki/docker-sync-on-Windows

**Comment by EugenMayer** [comment] 2017-05-11 20:24
i updated the sync guide https://github.com/EugenMayer/docker-sync/wiki/8.-Strategies and the installation guide https://github.com/EugenMayer/docker-sync/wiki/8.-Strategies and the home https://github.com/EugenMayer/docker-sync/wiki to fit the splitting

**Comment by ignatiusreza** [comment] 2017-05-11 23:57
yup, I'll take a look at this :+1:

**Comment by EugenMayer** [comment] 2017-05-12 15:45
@ignatiusreza who should use rsync under linux?

**Comment by ignatiusreza** [comment] 2017-05-12 21:56
Can't think of a reason why, but since the strategy is there, shouldn't we check if it works? Or should we just declare it not supported?

**Comment by EugenMayer** [comment] 2017-05-14 11:34
@ignatiusreza the only reason that would be needed if you actually do "remote" stuff, so you develop remote and sync using docker-sync.

This is already used by @mickaelperrin AFAIK so if we do that, it should have this goal - provide it for remote-usage. Using this locally is absolut nonsense

**Comment by ignatiusreza** [comment] 2017-05-15 00:43
hmmm.. not sure how remote->local sync would work using docker-sync.. does it mean that none of the remote or local are in docker container? maybe @mickaelperrin can elaborate?

**Comment by EugenMayer** [comment] 2017-05-15 06:23
@ignatiusreza local->remote is what rsync can do, local<->remote is what unison can do, since it is a both ways socket connection @ignatiusreza

**Comment by ignatiusreza** [comment] 2017-05-15 06:39
yes, that's how I understand it.. so when you said `actually do "remote" stuff, so you develop remote and sync using docker-sync.`.. do you meant to sync into local? or sync into a container inside the remote host? if it is inside the remote host.. I don't see how that's different with syncing from local host into local container?

well, I tried to use rsync using the boilerplate, and it's failing since authentication is required.. if we agreed that using rsync under linux doesn't make sense, then I'll update the rsync section to say just that.. wdyt?

**Comment by EugenMayer** [comment] 2017-05-15 06:43
@ignatiusreza you sync to a remote container, yes, but no its not the same as local in linux.

Since you do volume mounts in linux, this does only work locally - while rsync/unison can actually work remotely using the network, even though they are used on the local stack in macOS.

So there is a point getting this running, but lets put it like this - update the docs and point to this issue, which we will close and write something like "not yet supported, can be done. Want to help? issue"

wdyt?

**Comment by ignatiusreza** [comment] 2017-05-15 09:10
akh, I see what you mean.. 

To actually support rsync, we need to either update the strategy to include username & password, or to pass around public-key for authentication with rsync..

so, I agree, for now, let's just write it as not yet supported.. wiki updated!

**Comment by EugenMayer** [comment] 2017-05-15 16:08
i would suppose we can close this?

**Comment by codycraven** [comment] 2017-05-15 18:42
This morning I attempted to align the configuration for a project using docker-sync on Mac and Linux by now using docker-sync on Linux as well.

Doing this I ran into two issues:

1. Running any docker-sync command would give me `mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h` - I had to install the ruby-dev package in my OS to resolve.
2. This isn't a problem caused by docker-sync, however it is a variance between host OS's: Docker on Linux does not translate volume ownership/group to match the host user. For example, if I use docker-sync to mount a volume with a userid, such as 82 then any files created within the container will have 82 as the owner in the host, instead of the Linux user running the docker command.

**Comment by ignatiusreza** [comment] 2017-05-16 01:01
@EugenMayer let's close this, since the initial support works and is documented..

@codycraven let's have both of those reported as 2 separate issues so that we can tackle both individually.. for `1.` can you open an issue with the full stack-trace? I wonder where it got triggered from and if we can avoid it.. for `2.`, I need to look deeper into this.. since under Linux, we're using native volume create, we're bounded to what is supported by it.. IIUC, since we're using the local driver when mounting, we should be able to use uid/gid mount options to control ownership/group..

**Closed by ignatiusreza** 2017-05-16 01:01 UTC
Labels: documentation
