### ISSUE TITLE
Automatic macfsevents installation failed when Python 2 and 3 is installed

### ISSUE THREAD

**Issue by mobilizer** [EugenMayer/docker-sync#275] opened 2017-03-21 08:13 UTC
Automatic macfsevents installation on `docker-sync start` still failed for me when Python 2 and Python 3 is installed.

```
Requirement already satisfied: macfsevents in /usr/local/lib/python3.6/site-packages
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named fsevents
       error  Somehow could not successfully install macfsevents even though i treed. 
```

Fixed it by installing macfsevents for Python 2 manually:

     pip2 install macfsevents

**Comment by EugenMayer** [comment] 2017-03-21 16:58
- Which OSX version do you have? 
- how many pythons do you have installed? ( `which python` )
- which python is the default python?

**Comment by mobilizer** [comment] 2017-03-21 17:30
- OS X EC
- Python 2.7 and 3.6
- Default ist Python 2

**Comment by EugenMayer** [comment] 2017-03-22 05:40
Well if you installed both view brew, you have 3 including the system python?

**Comment by mobilizer** [comment] 2017-03-22 08:50
Exactly. 

- System
- Two in brew: python and python3

Default is brew python (2.7)

```
which python
/usr/local/bin/python
```

**Comment by EugenMayer** [comment] 2017-03-22 16:36
Pretty unusual setup i would suppose, installing p2 on osx .. not sure what could potentially go wrong here, cannot really reproduce this.

If you can debug this, you would do me a huge favour, if not, i guess i would close this issue as 'known issue' since it's not really critical

**Comment by EugenMayer** [comment] 2017-03-27 12:38
closing for now, not a high interest issue and also very hard to reproduce. Reopen if you want to start working on this

**Closed by EugenMayer** 2017-03-27 12:38 UTC
