### ISSUE TITLE
Error starting sync, exit code 23

### ISSUE THREAD

**Issue by tux240** [EugenMayer/docker-sync#151] opened 2016-10-03 22:39 UTC
> Error starting sync, exit code 23

I get this error when I save a file (host file) managed by docker-sync.
Even if I do a chmod 777 on the mounted volume, It find its old permissions.

The output from ls command in the rsync container:
`ls-l`
`-rwxr-xr-x    1 nobody   nogroup        532 Oct  3 20:52 README.md`

**Comment by EugenMayer** [comment] 2016-10-26 12:29
@tux240 not really sure what this issue is about, can you please re-declare what you mean and what the issue is?

**Comment by yogin** [comment] 2016-11-02 06:15
I just started using docker-sync and saw similar error when using the default rsync configuration

This is what the output looks like:
```
          ok  Starting rsync
rsync: failed to set permissions on "app/views/company_domain/store" (in volume): Not supported (95)
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/main.c(996) [sender=2.6.9]
       error  Error starting sync, exit code 23
     message
     success  Rsync server started
```

It turns out rsync was having issues transfering symbolic links, in a few places I have symlinks to files or directories, and after looking at the rsync documentation, found there's a few arguments one can pass to rsync to help with this.

I tried using `--links` first, but that didn't help, so replaced it with `--copy-links --hard-links`, so that in my docker-sync.yml file I now have

```
    sync_args: '-v --copy-links --hard-links'
```

And this seems to make rsync happy for me. 
Hope that helps someone.

BTW, thanks for docker-sync, setting it up was trivial, and I feel I can finally use docker for local development. Will be playing around with it in the coming weeks and see how it goes. 👍

**Comment by EugenMayer** [comment] 2016-11-02 06:59
Very interesting - we were already working on symlink issues but i have the feeling, that this is not solveable for all at the same time. The question is, what are the best defaults - put that into docker-sync and create a wiki page about that

**Comment by yogin** [comment] 2016-11-02 07:36
As I was setting up syncs, I was reading through the various options supported in the `docker-sync.yml` file in the [wiki](https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration), when I noticed `sync_args` I pretty much immediately went looking for the rsync documentation and see what options I could pass in.

But it might make sense to list some useful/common options for the various strategies, or maybe just putting links to the man pages for those tools.

**Comment by EugenMayer** [comment] 2016-11-15 10:08
@yogin any working points on this issue??

**Comment by dmitrybelyakov** [comment] 2016-11-18 12:24
Had same issue and `sync_args: '-v --copy-links --hard-links'` really helped

**Comment by carakas** [comment] 2016-11-19 12:52
does anybody know how to get it working with unison?

**Comment by EugenMayer** [comment] 2016-11-23 07:58
@carakas unison should work with symlinks right away. Otherwise google a bit, you find several options to tune it -if things fail, please open a new issue.

I will close this issue since there is a solution for rsync

**Closed by EugenMayer** 2016-11-23 07:58 UTC
Labels: feature, help wanted

**Comment by robsonrobi** [comment] 2017-06-30 15:35
Using `sync_args: '-v --copy-links --hard-links'` in my setup is not working, because some resolving urls are wrong.. is there any change to get rid of nogroup? In my case an apache is working and news files are created in the group application which is not good having nogroup.
