### ISSUE TITLE
docker for mac stable Version 17.12.0-ce-mac46 (21698) seems to break docker-sync

### ISSUE THREAD

**Issue by acima** [EugenMayer/docker-sync#518] opened 2018-01-10 18:26 UTC
!!!! Important hint !!!!!

> Please do not create issues for [docker](https://docs.docker.com/) or [docker-compose](https://docs.docker.com/compose/reference) related questions. Ensure you understand the tools properly and consult their documentation first. Please understand what [docker volumes](https://docs.docker.com/engine/admin/volumes/volumes/) / [docker-compose volumes](https://docs.docker.com/compose/compose-file/compose-file-v2/#specifying-byte-values)

> Please be sure to have a look at our [documentation](https://github.com/EugenMayer/docker-sync/wiki) too, especially [configuration](https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration) and our starting point the [boilerplate](https://github.com/EugenMayer/docker-sync-boilerplate)

### Error/Feature Requestion/Docs
max_attempt is set to 40 - but this error comes out in just a few seconds.

Alan-Cima:udemy-django alancima$ docker-sync start
          ok  Starting unison for sync django-sync
          ok  django-sync container not running
          ok  creating django-sync container
     command  docker run -p '::5000' -v django-sync:/app_sync -e VOLUME=/app_sync -e TZ=${TZ-`readlink /etc/localtime | sed -e 's,/usr/share/zoneinfo/,,'`} -e UNISON_EXCLUDES="-ignore='Regex .*/__pycache__/.*' -ignore='Regex \.gitignore' -ignore='Regex \.git/.*'"  --name django-sync -d eugenmayer/unison
          ok  starting initial sync of django-sync
     command  docker inspect --format='{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}' django-sync
     command  unison -testserver /app_sync "socket://:32772"
/Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:191:in `block in start_container': Failed to start unison container in time, try to increase max_attempt in your configuration. See https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration for more informations (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:187:in `loop'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_strategy/unison.rb:187:in `start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_process.rb:107:in `start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:92:in `block in start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:91:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/lib/docker-sync/sync_manager.rb:91:in `start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:166:in `daemonize'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/tasks/sync/sync.thor:48:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.6/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:23:in `load'
	from /usr/local/bin/docker-sync:23:in `<main>'

### Docker Driver
d4m

### Sync strategy
unison

### your docker-sync.yml
version: "2"

options:
  compose-file-path: './docker-compose.yml'

  # Optional: Activate this if you need to debug something. The default is false.
  # IMPORTANT: Do not run stable with this; it creates a memory leak. Turn off verbose when you are
  # done testing.
  verbose: true 

  max_attempt: 40

syncs:
  django-sync:
    src: '.'
    sync_excludes_type: 'Regex'
    sync_excludes: ['.*/__pycache__/.*', '\.gitignore', '\.git/.*']
    watch_excludes: ['.*/__pycache__/.*', '.*/.git', '.gitignore']

### OS
10.12.6

**Comment by EugenMayer** [comment] 2018-01-10 18:31
dupe of https://github.com/EugenMayer/docker-sync/issues/517

**Closed by EugenMayer** 2018-01-10 18:31 UTC

**Comment by acima** [comment] 2018-01-10 18:33
Sorry - that title didn't match for me - since synchronization never starts for me.

**Comment by EugenMayer** [comment] 2018-01-10 18:35
if downgrade works, its the same issue, its timing based
