### ISSUE TITLE
Unexpected behaviour of OpenStruct with docker-sync gem

### ISSUE THREAD

**Issue by rohit4813** [EugenMayer/docker-sync#723] opened 2020-04-03 09:43 UTC
### Error
Upon installing the gem, OpenStruct class starts inheriting from MakeMakefile class which implements various methods.

docker-sync has MakeMakefile as one of the dependencies which is required in the file:
.../lib/docker-sync/dependencies.rb

Since, OpenStruct relies upon 'method_missing' method, if any such method is called via its object which is implemented in MakeMakefile, the expected behaviour changes.

Example:
2.5.5 :003 > os = OpenStruct.new(message: 'halo', mess: 'world')
 => #<OpenStruct message="halo", mess="world">
2.5.5 :004 > os.mess
 => "world"
2.5.5 :005 > os.message
 => #<IO:<STDOUT>>
2.5.5 :006 > os['message']
 => "halo"

2.5.5 :013 > os = OpenStruct.new(message: 'halo', mess: 'world', cc_command: 'tada', link_command: 'hmm')
 => #<OpenStruct message="halo", mess="world", cc_command="tada", link_command="hmm">
2.5.5 :014 > os.link_command
Traceback (most recent call last):
        1: from (irb):14
ArgumentError (wrong number of arguments (given 0, expected 1..3))

Is this a known issue?
Is there any way to bypass this, i.e. OpenStruct to behave as expected?

### Docker Driver
d4m

### Sync strategy
native_osx

### your docker-sync.yml
version: "2"
options:
  compose-file-path: 'docker-compose.yml'
syncs:
  app-files:
    notify_terminal: true
    sync_strategy: 'native_osx'
    src: '.'
    sync_excludes: ['.git', 'log', 'node_modules', 'data', 'tmp','coverage', 'log', 'db', '.idea','app/assets']

### OS
OSX 10.14.6

**Comment by rohit4813** [comment] 2020-04-03 09:46
with gem
[OpenStruct,
 BSON::OpenStruct,
 ActiveSupport::ToJsonWithActiveSupportEncoder,
 Object,
 Shoulda::Callback::Matchers::RailsVersionHelper,
 Mongoid::Criteria::Queryable::Extensions::Object,
 Mongoid::Extensions::Object,
 BSON::Object,
 ActiveSupport::Dependencies::Loadable,
 InteractiveEditor::Editors,
 V8::Conversion::Object,
 MakeMakefile,
 ActiveSupport::Tryable,
 PP::ObjectMixin,
 JSON::Ext::Generator::GeneratorMethods::Object,
 Kernel,
 BasicObject]

without gem
 [OpenStruct,
 BSON::OpenStruct,
 ActiveSupport::ToJsonWithActiveSupportEncoder,
 Object,
 Shoulda::Callback::Matchers::RailsVersionHelper,
 Mongoid::Criteria::Queryable::Extensions::Object,
 Mongoid::Extensions::Object,
 BSON::Object,
 ActiveSupport::Dependencies::Loadable,
 InteractiveEditor::Editors,
 V8::Conversion::Object,
 ActiveSupport::Tryable,
 PP::ObjectMixin,
 JSON::Ext::Generator::GeneratorMethods::Object,
 Kernel,
 BasicObject]

**Comment by EugenMayer** [comment] 2020-04-04 07:33
Well to be honest, i do neither no a lot about what you encounter nor how to possible work around it do you have any suggestions?

Are you using docker-sync as a library?

**Comment by rohit4813** [comment] 2020-04-05 16:11
We were dockerising one of the many services that we use.

One way of bypassing this would be monkey-patching the keys in OpenStruct which we want to make sure it works as expected, this might not be the optimised way.

Inheriting MakeMakefile just adds to the list of keys which cannot be used for OpenStruct for its expected behaviour like 'to_s', 'pretty_print', ... etc.

This is not a major issue, just a little inconvenience.
Most likely we will let it be as it is, unless we opt for monkey-patching for some of the keys, not sure at the time being.

**Comment by ralbt** [comment] 2020-04-06 03:56
> Well to be honest, i do neither no a lot about what you encounter nor how to possible work around it do you have any suggestions?
> 
> Are you using docker-sync as a library?

The gem,docker-sync, has been added to a rails application. When you open a rails console and declare an OpenStruct object as mentioned by @rohit4813 

2.5.5 :003 > os = OpenStruct.new(message: 'halo', mess: 'world')
=> #<OpenStruct message="halo", mess="world">
2.5.5 :004 > os.mess
=> "world"
2.5.5 :005 > os.message
=> #<IO:>
2.5.5 :006 > os['message']
=> "halo"

The message value is not the same we have declared. It is getting overridden by the MakeMakefile throughout the application

**Comment by ralbt** [comment] 2020-04-06 04:19
@EugenMayer You can reproduce this in irb 

Steps to reproduce:

- Install a docker-sync gem
- Require **docker-sync** & **ostruct**
- Declare OpenStruct with the **message** key
- Read the message key from OpenStruct


irb(main):001:0> require 'ostruct'
=> true

irb(main):002:0> **o=OpenStruct.new(message: 'my message')**
=>  #\<OpenStruct message="my message">
irb(main):003:0> o.message
**=> "my message"**                             


irb(main):006:0> **require 'docker-sync'**
=> true
irb(main):007:0> **o=OpenStruct.new(message: 'my message')**
=> #\<OpenStruct message="my message">
irb(main):008:0> **o.message**
=> **#\<IO:\<STDOUT>>**
irb(main):009:0>

**Comment by ralbt** [comment] 2020-04-09 05:04
@EugenMayer Any update on this?

**Comment by EugenMayer** [comment] 2020-04-09 05:31
Sorry, not working on this. I never design docker-sync to be added to a rails runtime or whatever, i do not know the side effects of rails on this, considering how ruby-developers decided "magic should work" there is no way to mitigate all the possible issues with what and how rails does imply it's magic on other things.

This said, you will rely on yourself fixing this, this is too far from the usual use case or designed use case IMHO - sorry

**Comment by EugenMayer** [comment] 2020-04-23 05:43
I would close this issue as wont fix / not intended. Any hints?

**Closed** 2020-07-09 18:43 UTC
