### ISSUE TITLE
0.3 high cpu usage, slow update - unox watchdog issue

### ISSUE THREAD

**Issue by VSilantyev** [EugenMayer/docker-sync#308] opened 2017-04-26 06:48 UTC
Hi, thank you for the great work.

After updating to 0.3.2 I'm experiencing slow updates. Typically, before 0.3.2 files were synced almost instantly, after I touched them, I think in 0.2 secs.

Now each file change requires 2-3 seconds to sync.  I tried to debug:

Typical scenario:
- touch file on mac
- immediately python process appears in top with 100% cpu, for about 2 seconds
- then docker-sync says "Looking for changes"

How can I speed things up? Is this normal speed?

**Comment by EugenMayer** [comment] 2017-04-26 08:09
The only reason this could have is, that unox switch from macfsevents to watchdog.
Can you verify, when downgrading, that speed is stillt he same? 

The point with downgrading is, that unox ( still the new version ) will be used. That said, if you downgrade and things stay, it must be unox.

Do you have issues propagating changes on the host or in the container?

**Comment by EugenMayer** [comment] 2017-04-26 08:12
i am talking about https://github.com/hnsl/unox/pull/8

You could "downgrade" unison by 'brew uninstall unox" and then

    wget https://raw.githubusercontent.com/hnsl/unox/a94501d6231a50eb501fc90ef7281f6721277c60/unox.py
    sudo mv unox.py /usr/local/bin/unison-fsmonitor
    sudo chmod +x /usr/local/bin/unison-fsmonitor

**Comment by VSilantyev** [comment] 2017-04-26 08:47
Not working
```bash
docker-sync-stack start 
Error: No such keg: /usr/local/Cellar/unox
       error  You install unison-fsmonitor (unox) not using brew. Please uninstall it and run docker-sync again, so we can install it for you
       error  exit
```

**Comment by VSilantyev** [comment] 2017-04-26 09:35
Hmm.. Should I downgrade docker-sync ?

**Comment by EugenMayer** [comment] 2017-04-26 09:48
brew install unox
    where unison-fsmonitor

now move the patched unison over the brew one

    sudo mv /usr/local/bin/unison-fsmonitor /usr/local/Cellar/... ( what where returned )

that should do it

**Comment by VSilantyev** [comment] 2017-04-26 09:56
Figured it out.

- I've downgraded docker-sync to 0.2.3
- installed unox from this revision:
https://raw.githubusercontent.com/hnsl/unox/d0049abffb0ee1e5ac1f8ad3ed2a1ff8b8149daa/unox.py
It is latest revision with fsevents (your link above is using watchdog)

Now I got my speed back! Synchronisation starts instantly after file touch.

Thank you.
I will check on my coworker mac, does he have the same slowdowns.

**Comment by EugenMayer** [comment] 2017-04-26 09:59
@VSilantyev please help us a little more

now please upgrade to 0.3.5 - i expect the speed to stay the same, since you use the old unox. Can you confirm this?

**Comment by VSilantyev** [comment] 2017-04-26 11:50
Confirmed. 0.3.5 + old unox - speed is good.

**Comment by EugenMayer** [comment] 2017-04-26 12:36
Lets see if more can confirm this, thank hyou for your time

**Comment by mm4492** [comment] 2017-04-29 16:48
I can confirm this. I was having really slow updates (sometimes 60 seconds+) before it would trigger a sync. I downgraded unox using link from  @VSilantyev 

Basically....
````
wget https://raw.githubusercontent.com/hnsl/unox/d0049abffb0ee1e5ac1f8ad3ed2a1ff8b8149daa/unox.py
sudo mv unox.py /usr/local/bin/unison-fsmonitor
sudo chmod +x /usr/local/bin/unison-fsmonitor
````

Once I did that no problems.

**Comment by EugenMayer** [comment] 2017-04-29 16:51
Thanks for the feedback, we are already discussion this in https://github.com/hnsl/unox/issues/17 and its really important to gather some data. 

@mm4492 how many files do you watch/sync?
@VSilantyev how many do you have?

I need to gather this to understand what happens in which scenarios. It seems like whatdog is rather "less flaky" as macfsevents, though i had never issues with the latter anyway.

**Comment by mm4492** [comment] 2017-04-29 17:35
It's a pretty new symfony project so not too many. I thought it might have been the var/cache folder which I eventually excluded in sync_excludes: []

**Comment by EugenMayer** [comment] 2017-04-30 11:34
@mm4492 @VSilantyev could you count it with

```find ./src -type f ¦ wc -l```

Do change the "path"

**Comment by VSilantyev** [comment] 2017-05-02 04:01
I'm an extremist - 195310 files.

BTW, I'm not so happy with switch to the old version - it stops sync randomly, with error:
```bash
Fatal error: Server: Filesystem watcher error: error while handling events: Resource temporarily unavailable [read]

The watcher can be disabled by setting preference 'watch' to false
```

I can't remember this problems on 2.X versions, may be I somehow damaged python ecosystem when downgraded unox?

BTW, what versions of the python do you have?

**Comment by EugenMayer** [comment] 2017-05-02 07:04
No, compared to 2.x only unox changed. 187k files is too much, no way you will be able to get this run properly. Use excludes to limit the amount of files you sync. What hardware do you have, CPU, disks ram?

**Comment by VSilantyev** [comment] 2017-05-02 07:37
I have excluded .git, now 116k files.  
There are nothing more to exclude.
Hardware: MacBook Pro (Retina, 15-inch, Mid 2015), i7@2.8, 16gb, ssd

**Comment by EugenMayer** [comment] 2017-05-02 19:06
the problem with the excludes is, that the excludes do not count for the watcher, that makes things still bad for such sizes - but better as also syncing them.

I have some new ideas in mind to fix those things in then near future, lets see how things work out.

I have more sense and signals, that watchdog can be a big slower, but is much more robust and never looses a sync. I would for no prefer this over macfsevents pure performance with glitches from time to time.

I will close this discussion for now, feel free to reopen if the POV changes or we have new facts to consider

**Closed by EugenMayer** 2017-05-02 19:06 UTC
Labels: bug, feature
